nelmio_api_doc:
  documentation:
#    host: api.example.com
#    schemes: [http, https]
    info:
      title: Point Cash API
      description: Point Cash API doc
      version: 1.0.0
    securityDefinitions:
      Bearer:
        type: apiKey
        description: 'Authorization: Bearer {jwt}'
        name: Authorization
        in: header
    security:
      - Bearer: []
  areas: # to filter documented areas
    path_patterns:
      - ^/(?!/doc$) # Accepts routes under / except /doc